path_server_config = "scripts_python/training_FL/ADNI_fedavg_with_wandb/config/server.toml"
num_rounds = 3
n_client = 8
fraction_fit = 1.0
fraction_evaluate = 1.0
keep_labels_proportion = true
centralized_evaluation = false

[wandb_config]
wandb_training = true
project_name = "test_code"
model_artifact_name = "test_artifact"
log_freq = 1
metrics_to_log_from_clients = [ "accuracy_train accuracy_validation",]
debug = true
