batch_size = 128
lr = 0.001
epochs = 5
use_scheduler = true
device = "mps"
epoch_to_save_model = 6
path_to_save_model = "model_weights_ADNI"
measure_metrics_during_training = true
print_var = true
seed = 821285970
wandb_training = false
notes = ""
log_freq = 1
debug = false
use_weights_with_lower_validation_error = true

[lr_scheduler_config]
name = "ExponentialLR"
gamma = 0.9
