use_normalization = true
n_samples = 19200
# n_samples = 6400
merge_AD_class = 1
load_data_in_memory = false
load_data_type = 0
percentage_train = 0.7
percentage_validation = 0.15
percentage_test = 0.15
grey_scale_image = true
