# General training parameters
# Optimizer and lr scheduler have their own separate config files.
# The lr is set inside 
batch_size = 131
epochs = 50000
use_scheduler = true
device = "mps"
epoch_to_save_model = -1
path_to_save_model = "model_weights/"
measure_metrics_during_training = true
print_var = true
seed = -1

# WandB parameters (i.e. used only if wandb_training is true)
wandb_training = true
notes = ""
log_freq = 1
debug = false
entity = "alberto_zancanaro_academic"
project_name = "DEBUG_DEMNET_CENT"
name_training_run = "Grokking (fixed LR, weight decay 1e-2, betas, batch 131)"
log_model_artifact = false
model_artifact_name = "model"

# VGG parameters (i.e. used only if vgg_training is true)
vgg_training = false
use_pretrained_vgg = false
use_vgg_normalization_values = true
vgg_training_mode = 1

# Swin parameters (i.e. used only if swin_training is true)
swin_training = false
use_pretrained_swin = true
use_swin_normalization_values = true
swin_training_mode = 1

# FL parameters (i.e. used only if fl_training is true)
fl_training = false
use_weights_with_lower_validation_error = true
