batch_size = 1
lr = 0.01
epochs = 1
use_scheduler = true
lr_decay_rate = 0.99
optimizer_weight_decay = 0.01
device = "cpu"
epoch_to_save_model = 1
path_to_save_model = "model_weights"
measure_metrics_during_training = false
print_var = true
wandb_training = true
project_name = ""
model_artifact_name = ""
log_freq = 1
name_training_run = ""
notes = ""
debug = false
