batch_size = 128
lr = 0.001
epochs = 3
use_scheduler = true
device = "cuda"
epoch_to_save_model = 10
path_to_save_model = "model_weights_ADNI"
measure_metrics_during_training = true
print_var = true
seed = 651155725
wandb_training = true
log_freq = 1
debug = false
project_name = "test_code"
model_artifact_name = "test_artifact"

[lr_scheduler_config]
name = "ChainedScheduler"

[lr_scheduler_config.list_config_schedulers.config_0]
name = "CosineAnnealingLR"
T_max = 10
eta_min = 1e-5

[lr_scheduler_config.list_config_schedulers.config_1]
name = "ExponentialLR"
gamma = 0.94
