num_rounds = 4
n_client = 3
fraction_fit = 1
fraction_evaluate = 1
keep_labels_proportion = true
centralized_evaluation = true
# metrics_to_log_from_clients = ['accuracy_train', 'accuracy_validation']
metrics_to_log_from_clients = []
metrics_plot_backend = 'wandb'
