batch_size = 96
lr = 0.01
epochs = 50
optimizer_weight_decay = 0.01
device = "mps"
epoch_to_save_model = 10
path_to_save_model = "model_weights"
measure_metrics_during_training = true
print_var = true
seed = -1
use_weights_with_lower_validation_error = true

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
# LR Scheduler settings

use_scheduler = true
[lr_scheduler_config]
name = 'ChainedScheduler'
[lr_scheduler_config.list_config_schedulers.config_1]
name = 'CosineAnnealingLR'
T_max = 8
eta_min = 1e-5
[lr_scheduler_config.list_config_schedulers.config_2]
name = 'ExponentialLR'
gamma = 0.92

